<?php

namespace AestheticStudio\CsvImporter\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;
use AestheticStudio\CsvImporter\Services\CsvParserService;

class CsvImportController extends Controller
{
    protected CsvParserService $csvParser;

    public function __construct(CsvParserService $csvParser)
    {
        $this->csvParser = $csvParser;
    }

    /**
     * Display the main CSV importer page.
     */
    public function index()
    {
        $tables = $this->getAvailableTables();

        return view('csv-importer::importer', compact('tables'));
    }

    /**
     * Handle the temporary CSV file upload, parse it, and get target table schema.
     */
    public function upload(Request $request)
    {
        $request->validate([
            'table' => 'required|string',
            'csv_file' => 'required|file|mimes:csv,txt,xlsx',
            'import_type' => 'required|string|in:insert,update',
        ]);

        $tableName = $request->input('table');
        $importType = $request->input('import_type', 'insert');
        $allowedTables = $this->getAvailableTables();

        if (!in_array($tableName, $allowedTables)) {
            return response()->json([
                'success' => false,
                'message' => 'The selected database table is invalid or not allowed.'
            ], 403);
        }

        try {
            $file = $request->file('csv_file');
            $parsed = $this->csvParser->parse($file->getRealPath());
            
            // Get database columns for the target table
            $dbColumns = Schema::getColumnListing($tableName);

            // Filter out common autogenerated columns to simplify the mapping list
            $filteredDbColumns = array_filter($dbColumns, function ($column) use ($importType) {
                $exclude = ['created_at', 'updated_at', 'deleted_at'];
                if ($importType === 'insert') {
                    $exclude[] = 'id';
                }
                return !in_array($column, $exclude);
            });

            // Perform smart auto-matching of CSV headers to DB columns
            $mappings = [];
            foreach ($parsed['headers'] as $header) {
                $mappings[$header] = $this->smartMatchHeader($header, $filteredDbColumns);
            }

            return response()->json([
                'success' => true,
                'headers' => $parsed['headers'],
                'rows' => $parsed['rows'],
                'db_columns' => array_values($filteredDbColumns),
                'mappings' => $mappings,
                'table' => $tableName,
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Error parsing CSV file: ' . $e->getMessage()
            ], 422);
        }
    }

    /**
     * Execute the final database import transaction.
     */
    public function import(Request $request)
    {
        $request->validate([
            'table' => 'required|string',
            'mappings' => 'required|array',
            'data' => 'required|array',
            'import_type' => 'required|string|in:insert,update',
        ]);

        $tableName = $request->input('table');
        $importType = $request->input('import_type', 'insert');
        $allowedTables = $this->getAvailableTables();

        if (!in_array($tableName, $allowedTables)) {
            return response()->json([
                'success' => false,
                'message' => 'The selected database table is invalid or not allowed.'
            ], 403);
        }

        $mappings = $request->input('mappings'); // e.g. ['CSV Header' => 'db_column']
        $data = $request->input('data');
        $dbColumns = Schema::getColumnListing($tableName);

        if ($importType === 'update') {
            if (!in_array('id', $mappings)) {
                return response()->json([
                    'success' => false,
                    'message' => 'The ID column is required and must be mapped for updating records.'
                ], 422);
            }
        }

        DB::beginTransaction();
        try {
            $insertedCount = 0;
            $updatedCount = 0;
            
            foreach ($data as $rowIndex => $row) {
                $rowData = [];
                $rowId = null;
                
                foreach ($mappings as $csvHeader => $dbColumn) {
                    if (empty($dbColumn)) {
                        continue; // Column not mapped
                    }
                    
                    if (!in_array($dbColumn, $dbColumns)) {
                        throw new \Exception("Database column '{$dbColumn}' does not exist on table '{$tableName}'.");
                    }

                    $value = $row[$csvHeader] ?? null;
                    
                    // Convert empty strings to null for database compatibility
                    if ($value === '') {
                        $value = null;
                    }
                    
                    if ($dbColumn === 'id') {
                        $rowId = $value;
                    }
                    
                    $rowData[$dbColumn] = $value;
                }

                if ($importType === 'update') {
                    if (empty($rowId)) {
                        throw new \Exception("Row " . ($rowIndex + 1) . " is missing a value for the required ID column.");
                    }

                    // Check if record exists
                    $exists = DB::table($tableName)->where('id', $rowId)->exists();
                    if (!$exists) {
                        throw new \Exception("Record with ID '{$rowId}' does not exist in '{$tableName}'.");
                    }

                    // Remove id from the update payload
                    $updatePayload = $rowData;
                    unset($updatePayload['id']);

                    // Add update timestamp if it exists on the table
                    if (in_array('updated_at', $dbColumns) && !isset($updatePayload['updated_at'])) {
                        $updatePayload['updated_at'] = now();
                    }

                    DB::table($tableName)->where('id', $rowId)->update($updatePayload);
                    $updatedCount++;
                } else {
                    if (empty($rowData)) {
                        continue; // Skip if no fields are mapped
                    }

                    // Add timestamps if they exist on the table
                    if (in_array('created_at', $dbColumns) && !isset($rowData['created_at'])) {
                        $rowData['created_at'] = now();
                    }
                    if (in_array('updated_at', $dbColumns) && !isset($rowData['updated_at'])) {
                        $rowData['updated_at'] = now();
                    }

                    // Insert the row
                    DB::table($tableName)->insert($rowData);
                    $insertedCount++;
                }
            }

            DB::commit();

            $message = $importType === 'update'
                ? "Successfully verified and updated {$updatedCount} records in '{$tableName}'."
                : "Successfully verified and imported {$insertedCount} records into '{$tableName}'.";

            return response()->json([
                'success' => true,
                'message' => $message
            ]);

        } catch (\Exception $e) {
            DB::rollBack();
            return response()->json([
                'success' => false,
                'message' => 'Import aborted. Database Error: ' . $e->getMessage()
            ], 422);
        }
    }

    /**
     * Export a specific database table's contents to a CSV file.
     */
    public function export(string $tableName)
    {
        $allowedTables = $this->getAvailableTables();

        if (!in_array($tableName, $allowedTables)) {
            abort(403, 'The selected database table is invalid or not allowed.');
        }

        $dbColumns = Schema::getColumnListing($tableName);
        $records = DB::table($tableName)->get();

        $headers = [
            'Content-Type' => 'text/csv',
            'Content-Disposition' => "attachment; filename={$tableName}_export_" . date('Y-m-d') . ".csv",
            'Pragma' => 'no-cache',
            'Cache-Control' => 'must-revalidate, post-check=0, pre-check=0',
            'Expires' => '0',
        ];

        $callback = function () use ($records, $dbColumns) {
            $file = fopen('php://output', 'w');
            
            // Write column headers
            fputcsv($file, $dbColumns);
            
            // Write records
            foreach ($records as $row) {
                $rowArray = [];
                foreach ($dbColumns as $column) {
                    $rowArray[] = $row->$column ?? '';
                }
                fputcsv($file, $rowArray);
            }
            
            fclose($file);
        };

        return response()->stream($callback, 200, $headers);
    }

    /**
     * Retrieve a JSON preview of the database table's structure and records.
     */
    public function preview(string $tableName)
    {
        $allowedTables = $this->getAvailableTables();

        if (!in_array($tableName, $allowedTables)) {
            return response()->json([
                'success' => false,
                'message' => 'The selected database table is invalid or not allowed.'
            ], 403);
        }

        try {
            $dbColumns = Schema::getColumnListing($tableName);
            $records = DB::table($tableName)->limit(100)->get();

            return response()->json([
                'success' => true,
                'columns' => $dbColumns,
                'rows' => $records
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Error reading table data: ' . $e->getMessage()
            ], 422);
        }
    }

    /**
     * Retrieve all available database tables based on package config restrictions.
     */
    protected function getAvailableTables(): array
    {
        $allowed = config('csv-importer.allowed_tables', []);
        
        if (!empty($allowed)) {
            return $allowed;
        }

        $excluded = config('csv-importer.excluded_tables', [
            'migrations', 'password_resets', 'password_reset_tokens', 
            'failed_jobs', 'personal_access_tokens', 'sessions', 
            'jobs', 'job_batches', 'cache', 'cache_locks'
        ]);

        $connection = Schema::getConnection();
        $driver = $connection->getDriverName();
        $tables = [];

        if (method_exists(Schema::class, 'getTables')) {
            $rawTables = Schema::getTables();
            $tables = array_map(fn($t) => is_array($t) ? $t['name'] : $t->name, $rawTables);
        } else {
            // Backward-compatible custom fallbacks for Laravel 9/10
            if ($driver === 'mysql') {
                $tables = array_map(fn($t) => current((array)$t), DB::select('SHOW TABLES'));
            } elseif ($driver === 'sqlite') {
                $tables = array_map(fn($t) => $t->name, DB::select("SELECT name FROM sqlite_master WHERE type='table'"));
            } elseif ($driver === 'pgsql') {
                $tables = array_map(fn($t) => $t->tablename, DB::select("SELECT tablename FROM pg_tables WHERE schemaname='public'"));
            } else {
                try {
                    $tables = $connection->getDoctrineSchemaManager()->listTableNames();
                } catch (\Throwable $e) {
                    $tables = [];
                }
            }
        }

        return array_values(array_filter($tables, function ($table) use ($excluded) {
            return !in_array($table, $excluded);
        }));
    }

    /**
     * Perform smart fuzzy-matching between a CSV header and database columns.
     */
    protected function smartMatchHeader(string $header, array $dbColumns): ?string
    {
        $cleanHeader = strtolower(trim($header));
        
        // Remove special characters, spaces, and underscores for clean comparison
        $normalize = function ($str) {
            return strtolower(preg_replace('/[^a-zA-Z0-9]/', '', $str));
        };

        $normalizedHeader = $normalize($cleanHeader);

        // 1. Direct or normalized exact match
        foreach ($dbColumns as $column) {
            if (strtolower($column) === $cleanHeader || $normalize($column) === $normalizedHeader) {
                return $column;
            }
        }

        // 2. Fuzzy match e.g. "email_address" -> "email"
        $synonyms = [
            'email' => ['mail', 'emailaddress', 'e-mail', 'email_address'],
            'phone' => ['telephone', 'phonenumber', 'cell', 'mobile', 'phone_number'],
            'name' => ['fullname', 'full_name', 'username', 'user_name'],
            'first_name' => ['firstname', 'first', 'fname'],
            'last_name' => ['lastname', 'last', 'lname'],
        ];

        foreach ($synonyms as $standardCol => $aliases) {
            if (in_array($normalizedHeader, $aliases) && in_array($standardCol, $dbColumns)) {
                return $standardCol;
            }
        }

        // 3. Substring matching
        foreach ($dbColumns as $column) {
            $normalizedCol = $normalize($column);
            if (str_contains($normalizedHeader, $normalizedCol) || str_contains($normalizedCol, $normalizedHeader)) {
                return $column;
            }
        }

        return null;
    }
}
